---
- hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
    - name: modules required for the playbook
      yum:
        name: ['aws-cli']
        state: present

    - name: aliases | root forwarding
      lineinfile:
        path: /etc/aliases
        mode: 0644
        owner: root
        group: root
        regexp: "^root:\\s*\\S+"
        line: "root: {{ contact }}"
      notify: newaliases

    - name: cron | HOME variable
      cronvar:
        cron_file: uiuc-vault
        name: HOME
        value: /
    - name: cron | MAILTO variable
      cronvar:
        cron_file: uiuc-vault
        name: MAILTO
        value: root
    - name: cron | PATH variable
      cronvar:
        cron_file: uiuc-vault
        name: PATH
        value: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
    - name: cron | SHELL variable
      cronvar:
        cron_file: uiuc-vault
        name: SHELL
        value: /bin/bash

    - name: sudo | configuration file
      file:
        path: /etc/sudoers.d/uiuc-vault
        state: touch
        mode: 0640
        owner: root
        group: root
    - name: sudo | admin privileges
      lineinfile:
        path: /etc/sudoers.d/uiuc-vault
        regexp: "^%\\Q{{ item|replace(' ', '\\ ')|lower }}\\E\\s"
        line: "%{{ item|replace(' ', '\\ ')|lower }} ALL=(ALL) NOPASSWD: ALL"
      with_items: "{{ sudo_admin_groups }}"

  handlers:
    - name: newaliases
      command: newaliases
    - name: ssh | reload
      service:
        name: sshd
        state: reloaded
    - name: sss | restart
      service:
        name: sssd
        state: restarted
