---
- hosts: all
  remote_user: ec2-user
  become: yes
  vars_prompt:
    - name: sss_bind_pass
      prompt: Enter the password for the bind user of SSS
      private: yes

  tasks:
    - name: cis | disable unused filesystems
      copy:
        dest: /etc/modprobe.d/uiuc-vault.conf
        mode: 0644
        owner: root
        group: root
        content: |
            install cramfs /bin/true
            install freevxfs /bin/true
            install jffs2 /bin/true
            install hfs /bin/true
            install hfsplus /bin/true
            install squashfs /bin/true
            install udf /bin/true
            install vfat /bin/true
    - name: cis | ensure gpgcheck is globally activated
      lineinfile:
        path: /etc/yum.repos.d/amzn-nosrc.repo
        regexp: '^gpgcheck='
        line: gpgcheck=1
        state: present
    - name: cis | ensure permissions on bootloader config are configured
      file:
        path: /boot/grub/menu.lst
        mode: 0600
        owner: root
        group: root
    - name: cis | ensure authentication required for single user mode
      lineinfile:
        path: /etc/sysconfig/init
        regexp: '^SINGLE='
        line: SINGLE=/sbin/sulogin
        state: present
    - name: cis | ensure interactive boot is not enabled
      lineinfile:
        path: /etc/sysconfig/init
        regexp: '^PROMPT='
        line: PROMPT=no
        state: present
    - name: cis | ensure suspicious packets are logged (all)
      sysctl:
        sysctl_file: /etc/sysctl.d/uiuc-vault.conf
        name: net.ipv4.conf.all.log_martians
        value: 1
        state: present
    - name: cis | ensure suspicious packets are logged (default)
      sysctl:
        sysctl_file: /etc/sysctl.d/uiuc-vault.conf
        name: net.ipv4.conf.default.log_martians
        value: 1
        state: present
    - name: cis | ensure permissions on /etc/crontab are configured
      file:
        path: /etc/crontab
        mode: 0600
        owner: root
        group: root
    - name: cis | ensure permissions on cron directories are configured
      file:
        path: /etc/{{ item }}
        mode: 0700
        owner: root
        group: root
        state: directory
      with_items:
        - cron.hourly
        - cron.daily
        - cron.weekly
        - cron.monthly
        - cron.d
    - name: cis | ensure at/cron is restricted to authorized users (allow)
      copy:
        dest: /etc/cron.allow
        mode: 0600
        owner: root
        group: root
        content: |
            ec2-user
    - name: cis | ensure at/cron is restricted to authorized users (deny)
      file:
        path: /etc/cron.deny
        state: absent
    - name: cis | ensure issue and issue.net files
      copy:
          dest: /etc/{{ item }}
          mode: 0644
          owner: root
          group: root
          content: |
              ====================================================================
              | This system is for the use of authorized users only.  Usage of   |
              | this system may be monitored and recorded by system personnel.   |
              |                                                                  |
              | Anyone using this system expressly consents to such monitoring   |
              | and is advised that if such monitoring reveals possible          |
              | evidence of criminal activity, system personnel may provide the  |
              | evidence from such monitoring to law enforcement officials.      |
              ====================================================================
      with_items:
          - issue
          - issue.net

    - name: ntp | configure
      copy:
        dest: /etc/ntp.conf
        mode: 0644
        owner: root
        group: root
        content: |
            # For more information about this file, see the ntp.conf(5) man page.

            # Record the frequency of the system clock.
            driftfile /var/lib/ntp/drift

            # Permit time synchronization with our time source, but do not
            # permit the source to query or modify the service on this system.
            restrict -4 default kod nomodify notrap nopeer noquery
            restrict -6 default kod nomodify notrap nopeer noquery

            # Permit association with pool servers.
            restrict source nomodify notrap noepeer noquery

            # Permit all access over the loopback interface.  This could
            # be tightened as well, but to do so would effect some of
            # the administrative functions.
            restrict 127.0.0.1
            restrict ::1

            # Use and prefer the UIUC time servers
            server ntp-0.gw.illinois.edu iburst
            server ntp-1.gw.illinois.edu iburst
            server ntp-2.gw.illinois.edu iburst

            # Reduce the maximum number of servers used from the pool.
            tos maxclock 5

            # Enable public key cryptography.
            #crypto

            includefile /etc/ntp/crypto/pw

            # Key file containing the keys and key identifiers used when operating
            # with symmetric key cryptography.
            keys /etc/ntp/keys

            # Specify the key identifiers which are trusted.
            #trustedkey 4 8 42

            # Specify the key identifier to use with the ntpdc utility.
            #requestkey 8

            # Specify the key identifier to use with the ntpq utility.
            #controlkey 8

            # Enable writing of statistics records.
            #statistics clockstats cryptostats loopstats peerstats

            # Enable additional logging.
            logconfig =clockall =peerall =sysall =syncall

            # Listen only on the primary network interface.
            interface listen eth0
            interface ignore ipv6

            # Disable the monitoring facility to prevent amplification attacks using ntpdc
            # monlist command when default restrict does not include the noquery flag. See
            # CVE-2013-5211 for more details.
            # Note: Monitoring will not be disabled with the limited restriction flag.
            disable monitor
      notify: ntp | restart

    - name: sss | install
      yum:
        name: sssd
        state: present
    - name: sss | enable at startup
      service:
        name: sssd
        enabled: yes
    - name: sss | configure
      copy:
        dest: /etc/sssd/sssd.conf
        mode: 0600
        owner: root
        group: root
        content: |
            [sssd]
            domains = LOCAL, ad.uillinois.edu
            services = nss, pam
            config_file_version = 2

            [nss]
            filter_groups = root, wheel
            filter_users = root, ec2-user

            [domain/LOCAL]
            id_provider = local
            auth_provider = local
            access_provider = permit

            [domain/ad.uillinois.edu]
            id_provider = ldap
            auth_provider = ldap
            access_provider = simple

            ; Providers we aren't going to use
            chpass_provider = none
            sudo_provider = none
            selinux_provider = none
            autofs_provider = none
            hostid_provider = none

            ldap_uri = ldap://ldap-ad-aws.ldap.illinois.edu
            ldap_schema = ad
            ldap_referrals = false
            ldap_id_use_start_tls = true
            ldap_tls_reqcert = never

            case_sensitive = false
            ignore_group_members = true
            ; ldap_group_nesting_level = 0
            ldap_use_tokengroups = true
            ; ldap_deref_threshold = 0

            ldap_default_bind_dn = {{ sss_bind_user }}
            ldap_default_authtok = {{ sss_bind_pass }}

            ; ID mapping parameters
            ldap_id_mapping = true
            ldap_idmap_range_min = 2000000
            ldap_idmap_range_max = 2002000000
            ldap_idmap_range_size = 40000000
            ldap_idmap_default_domain_sid = S-1-5-21-2509641344-1052565914-3260824488

            ; Access parameters
            simple_allow_groups = {{ sss_allow_groups }}

            ; General overrides
            override_homedir = /home/%d/%u
      notify: sss | restart
    - name: sss | authconfig
      command: authconfig --enablesssd --enablesssdauth --enablemkhomedir --update

    - name: ssh | configure
      copy:
        dest: /etc/ssh/sshd_config
        mode: 0644
        owner: root
        group: root
        content: |
            #	$OpenBSD: sshd_config,v 1.100 2016/08/15 12:32:04 naddy Exp $

            # This is the sshd server system-wide configuration file.  See
            # sshd_config(5) for more information.

            # This sshd was compiled with PATH=/usr/local/bin:/bin:/usr/bin

            # The strategy used for options in the default sshd_config shipped with
            # OpenSSH is to specify options with their default value where
            # possible, but leave them commented.  Uncommented options override the
            # default value.

            # If you want to change the port on a SELinux system, you have to tell
            # SELinux about this change.
            # semanage port -a -t ssh_port_t -p tcp #PORTNUMBER
            #
            #Port 22
            #AddressFamily any
            #ListenAddress 0.0.0.0
            #ListenAddress ::

            Protocol 2
            Ciphers aes256-ctr,aes192-ctr,aes128-ctr
            MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com

            HostKey /etc/ssh/ssh_host_rsa_key
            #HostKey /etc/ssh/ssh_host_dsa_key
            HostKey /etc/ssh/ssh_host_ecdsa_key
            HostKey /etc/ssh/ssh_host_ed25519_key

            # Ciphers and keying
            #RekeyLimit default none

            # Logging
            #SyslogFacility AUTH
            SyslogFacility AUTHPRIV
            LogLevel INFO

            # Authentication:

            LoginGraceTime 60
            PermitRootLogin no
            #StrictModes yes
            MaxAuthTries 4
            #MaxSessions 10

            #PubkeyAuthentication yes

            # The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
            # but this is overridden so installations will only check .ssh/authorized_keys
            AuthorizedKeysFile .ssh/authorized_keys

            #AuthorizedPrincipalsFile none

            #AuthorizedKeysCommand none
            #AuthorizedKeysCommandUser nobody

            # For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
            HostbasedAuthentication no
            # Change to yes if you don't trust ~/.ssh/known_hosts for
            # HostbasedAuthentication
            #IgnoreUserKnownHosts no
            # Don't read the user's ~/.rhosts and ~/.shosts files
            IgnoreRhosts yes

            # EC2 uses keys for remote access
            PasswordAuthentication yes
            PermitEmptyPasswords no

            # Change to no to disable s/key passwords
            #ChallengeResponseAuthentication yes
            ChallengeResponseAuthentication no

            # Kerberos options
            #KerberosAuthentication no
            #KerberosOrLocalPasswd yes
            #KerberosTicketCleanup yes
            #KerberosGetAFSToken no
            #KerberosUseKuserok yes

            # GSSAPI options
            #GSSAPIAuthentication no
            #GSSAPICleanupCredentials yes
            #GSSAPIStrictAcceptorCheck yes
            #GSSAPIKeyExchange no
            #GSSAPIEnablek5users no

            # Set this to 'yes' to enable PAM authentication, account processing,
            # and session processing. If this is enabled, PAM authentication will
            # be allowed through the ChallengeResponseAuthentication and
            # PasswordAuthentication.  Depending on your PAM configuration,
            # PAM authentication via ChallengeResponseAuthentication may bypass
            # the setting of "PermitRootLogin without-password".
            # If you just want the PAM account and session checks to run without
            # PAM authentication, then enable this but set PasswordAuthentication
            # and ChallengeResponseAuthentication to 'no'.
            # WARNING: 'UsePAM no' is not supported in Amazon Linux AMI and may cause several
            # problems.
            UsePAM yes

            #AllowAgentForwarding yes
            #AllowTcpForwarding yes
            #GatewayPorts no
            X11Forwarding no
            #X11DisplayOffset 10
            #X11UseLocalhost yes
            #PermitTTY yes
            #PrintMotd yes
            PrintLastLog yes
            #TCPKeepAlive yes
            #UseLogin no
            UsePrivilegeSeparation sandbox
            PermitUserEnvironment no
            #Compression delayed
            ClientAliveInterval 300
            ClientAliveCountMax 0
            #ShowPatchLevel no
            #UseDNS yes
            #PidFile /var/run/sshd.pid
            #MaxStartups 10:30:100
            #PermitTunnel no
            #ChrootDirectory none
            #VersionAddendum none

            # no default banner path
            Banner /etc/issue.net

            # Accept locale-related environment variables
            AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
            AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
            AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
            AcceptEnv XMODIFIERS

            AllowGroups {{ ssh_allow_groups }} wheel

            # override default of no subsystems
            Subsystem sftp	/usr/libexec/openssh/sftp-server

            # Example of overriding settings on a per-user basis
            #Match User anoncvs
            #	X11Forwarding no
            #	AllowTcpForwarding no
            #	PermitTTY no
            #	ForceCommand cvs server[root@sbutler1-vault-a ssh]#

      notify: ssh | reload

  handlers:
    - name: ntp | restart
      service:
        name: ntpd
        state: restarted
    - name: ssh | reload
      service:
        name: sshd
        state: reloaded
    - name: sss | restart
      service:
        name: sssd
        state: restarted
