---
- hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
    - name: configuration directory
      file:
        path: /vault/config
        mode: 0755
        owner: root
        group: root
        state: directory
    - name: logging directory
      file:
        path: /vault/logs
        mode: 0700
        owner: root
        group: root
        state: directory

    - name: tls key file
      copy:
        dest: /vault/config/server.key
        mode: 0600
        owner: root
        group: root
        content: "{{ tls_key }}"
    - name: tls certificate file
      copy:
        dest: /vault/config/server.crt
        mode: 0644
        owner: root
        group: root
        content: "{{ tls_crt }}"
    - name: tls LDAP CA file
      copy:
        src: ../incommon.pem
        dest: /vault/config/ldap-ca.crt
        mode: 0644
        owner: root
        group: root

    - name: configuration file
      copy:
        dest: /vault/config/config.hcl
        mode: 0644
        owner: root
        group: root
        content: |
            storage "dynamodb" {
                ha_enabled = "true"
                region = "{{ region }}"
                table = "{{ vault_storage }}"
            }

            # Only for the health check
            listener "tcp" {
                address = "127.0.0.1:8100"
                tls_disable = "true"
            }

            # Public listener
            listener "tcp" {
                address = "0.0.0.0:8200"
                cluster_address = "0.0.0.0:8201"

                tls_cert_file = "/vault/config/server.crt"
                tls_key_file = "/vault/config/server.key"
            }

            ui = "true"
            pid_file = "/vault/vault.pid"

            api_addr = "https://{{ api_addr }}:8200"
            cluster_name = "{{ project }}"
            cluster_addr = "https://{{ cluster_addr }}:8201"

    - name: logrotate | configure vault log rotation
      copy:
        dest: /etc/logrotate.d/vault
        mode: 0644
        owner: root
        group: root
        content: !unsafe |
            /vault/logs/*.log {
                daily
                rotate 30
                compress
                delaycompress
                nocreate
                sharedscripts
                postrotate
                    _container_id=`docker ps --filter "label=edu.illinois.ics.vault.role=server" --format '{{.ID}}' | head -n1`
                    if [ -n "$_container_id" ]; then
                        docker kill -s HUP $_container_id
                    fi
                endscript
            }
